import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import DefaultLayout from '../layout/DefaultLayout'

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>Aei.edu.lk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>

      </DefaultLayout>

    </React.Fragment>
  )
}
